services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
